export { default as Heading } from "./heading/Heading";
export { default as Text } from "./text/Text";
export { default as Container } from "./container/Container";
export { default as Button } from "./button/Button";
export { default as FormInput } from "./FormInput/FormInput";
export { default as SiteEditor } from "./siteEditor/SiteEditor";
// export { default as FromText } from "./FormInput/FormText";
export { default as Grid } from "./grid/Grid";
export { default as Banner } from "./banner/Banner";
export { default as WorkSeam } from "./workSeam/WorkSeam";
export { default as WorkSignature } from "./workSignature/WorkSignature";
export { default as ChoosingStampify } from "./choosingStampify/ChoosingStampify";
export { default as Faq } from "./faq/Faq";
export { default as AboutStampify } from "./aboutStampify/AboutStampify";
export { default as Input } from "./Input/Input";
export { default as ScreenView } from "./screenview/ScreenView";
